name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI [${{ matrix.target-arch }}]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target-arch:
          - x86_64

    env:
      TARGET_ARCH: ${{ matrix.target-arch }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install ECL
        run: |
          make setup/ecl
      
      - name: Install SBCL
        run: |
          make setup/sbcl

      - name: Build kernel [${{ matrix.target-arch }}]
        run: |
          make kernel

      - name: Build [${{ matrix.target-arch }}]
        run: |
          make build

      - name: Upload image
        uses: actions/upload-artifact@v7
        with:
          name: ecclesia-${{ matrix.target-arch }}
          path: build/*
          compression-level: 9 # maximum compression

      - name: Unit Tests
        run: |
          make test/unit
