name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI [${{ matrix.target-arch }}]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target-arch:
          - i386
          - x86_64

    env:
      TARGET_ARCH: ${{ matrix.target-arch }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install SBCL
        run: |
          make setup/sbcl

      - name: Build [${{ matrix.target-arch }}]
        run: |
          make build

      - name: Upload raw image
        uses: actions/upload-artifact@v7
        if: matrix.target-arch != 'aarch64'
        with:
          name: ecclesia-${{ matrix.target-arch }}
          path: ecclesia-${{ matrix.target-arch }}.img

      - name: Upload bin image
        uses: actions/upload-artifact@v7
        if: matrix.target-arch == 'aarch64'
        with:
          name: ecclesia-${{ matrix.target-arch }}
          path: ecclesia-${{ matrix.target-arch }}.bin

      - name: Unit Tests
        run: |
          make test/unit
